version: '3'

includes:
  remote: https://github.com/eoap/task-files/raw/refs/heads/main/build-test/Taskfile.yaml

tasks:

  test:
  - task: remote:test

  test-capture-json-stdout:
  - task: remote:test-by-index
    vars:
      VAR: 0