version: '3'

includes:
  remote: https://github.com/eoap/task-files/raw/refs/heads/main/build-test/Taskfile.yaml

tasks:

  all-workflows:
  - task: remote:test

  capture-json-stdout:
  - task: remote:test-by-index
    vars:
      VAR: 0

  conditional-native:
  - task: remote:test-by-index
    vars:
      VAR: 7

  conditional-epsg-4326:
  - task: remote:test-by-index
    vars:
      VAR: 8